name: minio_plus
description: Unofficial updated Minio Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 0.0.1
homepage: "https://github.com/mhmdVoj/minio_plus"
issue_tracker: "https://github.com/mhmdVoj/minio_plus/issues"

environment:
  sdk: ">=2.12.0 <3.16.0"

dependencies:
  meta: ^1.11.0
  http: ^1.2.0
  crypto: ^3.0.3
  convert: ^3.1.1
  xml: ^6.0.1
  buffer: ^1.1.0
  intl: ^0.18.1
  mime: ^1.0.0
  path: ^1.9.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  html: ^0.15.0
